[package]
name = "interrupts"
version = "0.1.0"
edition = "2021"

[dependencies]
x86_64 = "0.14.2"

drivers = { path = "../drivers" }
[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
